In [69]:
import pandas
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
import time
import boto
from boto.s3.key import Key
import pandas as pd
from sqlalchemy import create_engine

In [70]:
filename_train = 'D:/Machine Learning/Bike sensor data/Test-Drive-Sasken/test-drive-ml-2_3_4.csv'
names_train = ['Speed','GyroScop_x','GyroScop_y','GyroScop_z','attitude_pitch','attitude_roll','attitude_yaw','acceleration_x','acceleration_y','acceleration_z','G_x_avg','G_y_avg','A_x_avg','A_y_avg','A_z_avg','marker']
data_train = pandas.read_csv(filename_train, names=names_train)

df_train = pd.DataFrame(data_train, columns=data_train.columns)
df_train = df_train.ix[1:]

df_train['is_train'] = np.random.uniform(0, 0, len(df_train)) <= .100
df_train.head()

Speed   GyroScop_x    GyroScop_y    GyroScop_z attitude_pitch attitude_roll  \
1  -3.6  0.561173856    0.04686249   0.092928469    0.554535052  -0.009908888   
2  -3.6  0.283138305   0.014048797  -0.160364747    0.595711616  -0.009801454   
3  -3.6   0.39914155  -0.143089995  -0.273033887    0.617707136  -0.001267816   
4  -3.6  0.395565838  -0.022679988  -0.119658746     0.64502564   0.006303429   
5  -3.6  0.062787458   0.299148381  -0.059119448    0.660259827    0.03877278   

   attitude_yaw acceleration_x acceleration_y acceleration_z G_x_avg G_y_avg  \
1   0.003412455    -0.01252646   -0.353105843    0.313467264       0       0   
2  -0.000722531   -0.100575335   -0.237562343    0.400585651       0       0   
3  -0.033180496   -0.089344271    -0.23768124    0.295691907       0       0   
4  -0.057348863   -0.057160962   -0.234474435    0.416118652       0       0   
5  -0.031739561   -0.089133799   -0.264561832    0.242226958       0       0   

  A_x_avg A_y_avg A_z_avg  marker is_train  
1       0       0       0  normal     True  
2       0       0       0  normal     True  
3       0       0       0  normal     True  
4       0       0       0  normal     True  
5       0       0       0  normal     True

In [71]:
from pymongo import MongoClient

conn = MongoClient('ec2-35-154-102-28.ap-south-1.compute.amazonaws.com',1234)
db = conn.get_database('sensor_data')
collection = db.get_collection('apple_sensor')
cursor = collection.find()
df_mongo =  pd.DataFrame(list(cursor))
del df_mongo['_id']

In [72]:
df_mongo = df_mongo[['speed','gyroscop_x','gyroscop_y','gyroscop_z','attitude_pitch','attitude_roll','attitude_yaw','acceleration_x','acceleration_y','acceleration_z','marker','trip_id','holizontalAccuracy','verticalAccuracy','altitude','longitude','latitude','timestamp']]
df_mongo['speed'] = df_mongo['speed'].astype('float') *(60.00000*60.00000/1000.00000)

In [73]:
df_mongo = df_mongo.sort_values('timestamp')
df_mongo = df_mongo.reset_index(drop=True)
df_mongo.rename(columns = {'speed':'Speed','gyroscop_x':'GyroScop_x','gyroscop_y':'GyroScop_y','gyroscop_z':'GyroScop_z'}, inplace = True)
df_mongo['G_x_avg'] = df_mongo['GyroScop_x'].rolling(window=50).mean().fillna(0)
df_mongo['G_y_avg'] = df_mongo['GyroScop_y'].rolling(window=50).mean().fillna(0)
df_mongo['A_x_avg'] = df_mongo['acceleration_x'].rolling(window=50).mean().fillna(0)
df_mongo['A_y_avg'] = df_mongo['acceleration_y'].rolling(window=50).mean().fillna(0)
df_mongo['A_z_avg'] = df_mongo['acceleration_z'].rolling(window=50).mean().fillna(0)
df_mongo['marker'].replace('No Button Pressed', 'normal',inplace=True)
df_mongo['marker'].replace('No Button Pressed ', 'normal',inplace=True)
df_test = df_mongo[['Speed','GyroScop_x','GyroScop_y','GyroScop_z','attitude_pitch','attitude_roll','attitude_yaw','acceleration_x','acceleration_y','acceleration_z','G_x_avg','G_y_avg','A_x_avg','A_y_avg','A_z_avg','marker','trip_id','holizontalAccuracy','verticalAccuracy','altitude','longitude','latitude','timestamp']]
df_test_copy = df_mongo[['Speed','GyroScop_x','GyroScop_y','GyroScop_z','attitude_pitch','attitude_roll','attitude_yaw','acceleration_x','acceleration_y','acceleration_z','G_x_avg','G_y_avg','A_x_avg','A_y_avg','A_z_avg','marker','trip_id','holizontalAccuracy','verticalAccuracy','altitude','longitude','latitude','timestamp']]

In [74]:
#-------------------------------------code to read test data from file----------------------------------------
#filename_test = 'D:/Machine Learning/Bike sensor data/Test-Drive-Sasken/test-drive-ml-5.csv'
#names_test = ['Speed','GyroScop_x','GyroScop_y','GyroScop_z','attitude_pitch','attitude_roll','attitude_yaw','acceleration_x','acceleration_y','acceleration_z','G_x_avg','G_y_avg','A_x_avg','A_y_avg','A_z_avg','marker','trip_id','holizontalAccuracy','verticalAccuracy','altitude','longitude','latitude','timestamp']
#data_test = pandas.read_csv(filename_test, names=names_test)

#df_test = pd.DataFrame(data_test, columns=data_test.columns)
#df_test = df_test.ix[1:]

#df_test_copy = pd.DataFrame(data_test, columns=data_test.columns)
#df_test_copy = df_test_copy.ix[1:]

#--------------------------------------------------------------------------------------

del df_test['trip_id']
del df_test['holizontalAccuracy']
del df_test['verticalAccuracy']
del df_test['altitude']
del df_test['longitude']
del df_test['latitude']
del df_test['timestamp']

df_test['is_train'] = np.random.uniform(0, 0, len(df_test)) <= .100

df_test_copy[['Speed','GyroScop_x','GyroScop_y','GyroScop_z','attitude_pitch','attitude_roll','attitude_yaw','acceleration_x','acceleration_y','acceleration_z','G_x_avg','G_y_avg','A_x_avg','A_y_avg','A_z_avg','holizontalAccuracy','verticalAccuracy','altitude','longitude','latitude','timestamp']] = df_test_copy[['Speed','GyroScop_x','GyroScop_y','GyroScop_z','attitude_pitch','attitude_roll','attitude_yaw','acceleration_x','acceleration_y','acceleration_z','G_x_avg','G_y_avg','A_x_avg','A_y_avg','A_z_avg','holizontalAccuracy','verticalAccuracy','altitude','longitude','latitude','timestamp']].astype('object')
df_test_copy[['marker','trip_id']] = df_test_copy[['marker','trip_id']].astype('string')

C:\Users\EE208958\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel\__main__.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [75]:
d1_test = df_test[df_test['is_train']==True]
d1_train= df_train[df_train['is_train']==True]

d1_test[['Speed','GyroScop_x','GyroScop_y','GyroScop_z','attitude_pitch','attitude_roll','attitude_yaw','acceleration_x','acceleration_y','acceleration_z','G_x_avg','G_y_avg','A_x_avg','A_y_avg','A_z_avg']] = d1_test[['Speed','GyroScop_x','GyroScop_y','GyroScop_z','attitude_pitch','attitude_roll','attitude_yaw','acceleration_x','acceleration_y','acceleration_z','G_x_avg','G_y_avg','A_x_avg','A_y_avg','A_z_avg']].astype('float')
d1_train[['Speed','GyroScop_x','GyroScop_y','GyroScop_z','attitude_pitch','attitude_roll','attitude_yaw','acceleration_x','acceleration_y','acceleration_z','G_x_avg','G_y_avg','A_x_avg','A_y_avg','A_z_avg']] = d1_train[['Speed','GyroScop_x','GyroScop_y','GyroScop_z','attitude_pitch','attitude_roll','attitude_yaw','acceleration_x','acceleration_y','acceleration_z','G_x_avg','G_y_avg','A_x_avg','A_y_avg','A_z_avg']].astype('float')

d1_train['marker'] = d1_train['marker'].astype('category')
d1_test['marker'] = d1_test['marker'].astype('category')

In [76]:
print('Number of observations in the training data:', len(d1_train))
print('Number of observations in the test data:',len(d1_test))

('Number of observations in the training data:', 4512)
('Number of observations in the test data:', 2324)


In [77]:
features = df_train.columns[:15]
features

Index([u'Speed', u'GyroScop_x', u'GyroScop_y', u'GyroScop_z',
       u'attitude_pitch', u'attitude_roll', u'attitude_yaw', u'acceleration_x',
       u'acceleration_y', u'acceleration_z', u'G_x_avg', u'G_y_avg',
       u'A_x_avg', u'A_y_avg', u'A_z_avg'],
      dtype='object')

In [78]:
y = pd.factorize(d1_train['marker'])[0]
x = pd.CategoricalIndex(d1_train['marker'])

#x.append(y.tolist)
#print(x[2100:2157])
#y[2100:2157]

In [79]:
clf = RandomForestClassifier(n_jobs=1000)

clf.fit(d1_train[features], y)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=1000, oob_score=False,
            random_state=None, verbose=0, warm_start=False)

In [80]:
test_data = clf.predict(d1_test[features])
test_data

array([0, 0, 0, ..., 0, 4, 0], dtype=int64)

In [81]:
proba = clf.predict_proba(d1_test[features])
print(proba)

[[ 1.   0.   0.   0.   0. ]
 [ 1.   0.   0.   0.   0. ]
 [ 1.   0.   0.   0.   0. ]
 ..., 
 [ 0.9  0.   0.   0.   0.1]
 [ 0.3  0.   0.1  0.1  0.5]
 [ 0.6  0.   0.   0.2  0.2]]


In [82]:
preds = clf.predict(d1_test[features])

In [83]:
sLength = len(df_test_copy['marker'])

#for x in np.nditer(preds):
df_test_copy['p_marker'] = pd.Series(preds , index=df_test_copy.index)

df_test_copy['p_marker'].replace(0, 'normal',inplace=True)
df_test_copy['p_marker'].replace(1, 'Right Turn',inplace=True)
df_test_copy['p_marker'].replace(2, 'Hard Acceleration',inplace=True)
df_test_copy['p_marker'].replace(3, 'Decceleration',inplace=True)
df_test_copy['p_marker'].replace(4, 'Left Turn',inplace=True)

In [84]:
#ts = int(time.time())
#data_file = df_test_copy.to_csv(str(ts)+".csv",index=False)

In [85]:
tb = pd.crosstab(d1_test['marker'], df_test_copy['p_marker'], rownames=['Actual Events'], colnames=['Predicted Events'])
#import matplotlib.pyplot as plt
#tb.plot()
#tb.to_csv(str(ts)+"_cross_table.csv")
#plt.show()
tb

Predicted Events   Decceleration  Hard Acceleration  Left Turn  Right Turn  \
Actual Events                                                                
Decceleration                156                 23          0           0   
Hard Acceleration              9                289          1           0   
Left Turn                      0                  0         23           0   
Right Turn                     0                  0          0          33   
normal                        24                 58          0           1   

Predicted Events   normal  
Actual Events              
Decceleration          29  
Hard Acceleration     100  
Left Turn              29  
Right Turn              7  
normal               1542

In [67]:
#keyId = "AKIAJM6HKMMJJO5MIK4Q"
#sKeyId= "j5RD68MBl5KYnKimWgrxxNSnvJzzazYFTMrGois+"
#fileName=str(ts)+".csv"
#bucketName="geo-code"
#files = open(str(ts)+".csv")
#conn = boto.connect_s3(keyId,sKeyId)
#bucket = conn.get_bucket(bucketName)
##Get the Key object of the bucket
#k = Key(bucket)
##Crete a new key with id as the name of the file
#k.key=fileName
##Upload the file
#result = k.set_contents_from_file(files)
##result contains the size of the file uploaded
#print('file uploaded successfully...')

In [68]:
df_test_copy['Line Group (Path ID)']= df_test_copy.index
df_test_copy['Order of Points']= df_test_copy.index

In [44]:
#df_test_copy

In [49]:
def f(row):
    if (row['marker'] == 'normal') & (row['p_marker'] == 'normal'):
        val = 'normal'
    elif row['marker'] == row['p_marker']:
        val = 'matched'
    else:
        val = 'not_matched'
    return val
        
df_test_copy['combined_marker'] = df_test_copy.apply(f, axis=1)
df_test_copy.to_csv("data.csv",index = False,header = True)

In [22]:
#---------------------------connection to postgres-----------------------------------
#import psycopg2, csv

#try:
 #   conn = psycopg2.connect("dbname='SensorFusionDatabase' user='sanni' host='sensorfusiondbinstance.cjz4wrixhzjb.us-west-2.rds.amazonaws.com' password='mysensorfusiondb'")
#   print("connected")
#except:
#    print ("I am unable to connect to the database")

#cur= conn.cursor()

#----------------------------faster way to insert data in postgres--------------------------------

#dataText = ','.join(cur.mogrify("(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)", tuple(row))for i, row in enumerate(reader))

#cur.execute('INSERT INTO "apple_sensor" VALUES ' + dataText)

#------------------------------slower way to insert data in postgres------------------------------

#reader = csv.reader(open('data.csv', 'r'))

#for i, row in enumerate(reader):
    #print(i, row)
#    if i == 0: continue

#    cur.execute('''
#       INSERT INTO "apple_sensor" (
#            "Speed","GyroScop_x","GyroScop_y","GyroScop_z","attitude_pitch","attitude_roll","attitude_yaw","acceleration_x","acceleration_y","acceleration_z","G_x_avg","G_y_avg","A_x_avg","A_y_avg","A_z_avg","marker","trip_id","holizontalAccuracy","verticalAccuracy","altitude","longitude","latitude","timestamp","p_marker","Line_Group","Order_of_Points","combined_marker"
#        ) values %s''', [tuple(row)]
 #   )

#conn.commit()
#cur.close()


In [23]:
(2064.000/2324.000)*100.000

88.81239242685027