In [25]:
import pandas
filename = 'D:/Machine Learning/Bike sensor data/Test-Drive-Sasken/test-drive-ml-3_4.csv'
names = ['Speed (Kmph)','GyroScop_x','GyroScop_y','GyroScop_z','attitude_pitch','attitude_roll','attitude_yaw','acceleration_x','acceleration_y','acceleration_z','G_x_avg','G_y_avg','A_x_avg','A_y_avg','A_z_avg','marker']
data = pandas.read_csv(filename, names=names)

In [26]:
# Load scikit's random forest classifier library
from sklearn.ensemble import RandomForestClassifier

# Load numpy
import numpy as np

# Load pandas
import pandas as pd

In [27]:
df = pd.DataFrame(data, columns=data.columns)
df = df.ix[1:]

In [28]:
df.head()

Speed (Kmph)   GyroScop_x    GyroScop_y    GyroScop_z attitude_pitch  \
1         -3.6  0.561173856    0.04686249   0.092928469    0.554535052   
2         -3.6  0.283138305   0.014048797  -0.160364747    0.595711616   
3         -3.6   0.39914155  -0.143089995  -0.273033887    0.617707136   
4         -3.6  0.395565838  -0.022679988  -0.119658746     0.64502564   
5         -3.6  0.062787458   0.299148381  -0.059119448    0.660259827   

  attitude_roll  attitude_yaw acceleration_x acceleration_y acceleration_z  \
1  -0.009908888   0.003412455    -0.01252646   -0.353105843    0.313467264   
2  -0.009801454  -0.000722531   -0.100575335   -0.237562343    0.400585651   
3  -0.001267816  -0.033180496   -0.089344271    -0.23768124    0.295691907   
4   0.006303429  -0.057348863   -0.057160962   -0.234474435    0.416118652   
5    0.03877278  -0.031739561   -0.089133799   -0.264561832    0.242226958   

  G_x_avg G_y_avg A_x_avg A_y_avg A_z_avg  marker  
1       0       0       0       0       0  normal  
2       0       0       0       0       0  normal  
3       0       0       0       0       0  normal  
4       0       0       0       0       0  normal  
5       0       0       0       0       0  normal

In [29]:
df['is_train'] = np.random.uniform(0, 1, len(df)) <= .75
# View the top 5 rows
df.head()

Speed (Kmph)   GyroScop_x    GyroScop_y    GyroScop_z attitude_pitch  \
1         -3.6  0.561173856    0.04686249   0.092928469    0.554535052   
2         -3.6  0.283138305   0.014048797  -0.160364747    0.595711616   
3         -3.6   0.39914155  -0.143089995  -0.273033887    0.617707136   
4         -3.6  0.395565838  -0.022679988  -0.119658746     0.64502564   
5         -3.6  0.062787458   0.299148381  -0.059119448    0.660259827   

  attitude_roll  attitude_yaw acceleration_x acceleration_y acceleration_z  \
1  -0.009908888   0.003412455    -0.01252646   -0.353105843    0.313467264   
2  -0.009801454  -0.000722531   -0.100575335   -0.237562343    0.400585651   
3  -0.001267816  -0.033180496   -0.089344271    -0.23768124    0.295691907   
4   0.006303429  -0.057348863   -0.057160962   -0.234474435    0.416118652   
5    0.03877278  -0.031739561   -0.089133799   -0.264561832    0.242226958   

  G_x_avg G_y_avg A_x_avg A_y_avg A_z_avg  marker is_train  
1       0       0       0       0       0  normal     True  
2       0       0       0       0       0  normal     True  
3       0       0       0       0       0  normal    False  
4       0       0       0       0       0  normal     True  
5       0       0       0       0       0  normal     True

In [30]:
# Create two new dataframes, one with the training rows, one with the test rows
train, test = df[df['is_train']==True], df[df['is_train']==False]
test[['Speed (Kmph)','GyroScop_x','GyroScop_y','GyroScop_z','attitude_pitch','attitude_roll','attitude_yaw','acceleration_x','acceleration_y','acceleration_z','G_x_avg','G_y_avg']] = test[['Speed (Kmph)','GyroScop_x','GyroScop_y','GyroScop_z','attitude_pitch','attitude_roll','attitude_yaw','acceleration_x','acceleration_y','acceleration_z','G_x_avg','G_y_avg']].astype('float')
train[['Speed (Kmph)','GyroScop_x','GyroScop_y','GyroScop_z','attitude_pitch','attitude_roll','attitude_yaw','acceleration_x','acceleration_y','acceleration_z','G_x_avg','G_y_avg']] = train[['Speed (Kmph)','GyroScop_x','GyroScop_y','GyroScop_z','attitude_pitch','attitude_roll','attitude_yaw','acceleration_x','acceleration_y','acceleration_z','G_x_avg','G_y_avg']].astype('float')
train['marker'] = train['marker'].astype('category')
test['marker'] = test['marker'].astype('category')

C:\Users\EE208958\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel\__main__.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\EE208958\AppData\Local\Continuum\Anaconda2\lib\site-packages\ipykernel\__main__.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [31]:
# Show the number of observations for the test and training dataframes
print('Number of observations in the training data:', len(train))
print('Number of observations in the test data:',len(test))

('Number of observations in the training data:', 2541)
('Number of observations in the test data:', 889)


In [32]:
features = df.columns[:12]

In [33]:
features

Index([u'Speed (Kmph)', u'GyroScop_x', u'GyroScop_y', u'GyroScop_z',
       u'attitude_pitch', u'attitude_roll', u'attitude_yaw', u'acceleration_x',
       u'acceleration_y', u'acceleration_z', u'G_x_avg', u'G_y_avg'],
      dtype='object')

In [34]:
y = pd.factorize(train['marker'])[0]
x = pd.CategoricalIndex(train['marker'])
print(x[200:257])
y[200:257]

CategoricalIndex([u'normal', u'normal', u'normal', u'normal', u'normal',
                  u'normal', u'normal', u'normal', u'normal', u'normal',
                  u'normal', u'RightTurn', u'RightTurn', u'RightTurn',
                  u'RightTurn', u'RightTurn', u'RightTurn', u'normal',
                  u'normal', u'HardAcceleration', u'HardAcceleration',
                  u'HardAcceleration', u'HardAcceleration',
                  u'HardAcceleration', u'HardAcceleration',
                  u'HardAcceleration', u'HardAcceleration',
                  u'HardAcceleration', u'HardAcceleration',
                  u'HardAcceleration', u'HardAcceleration',
                  u'HardAcceleration', u'Decceleration', u'Decceleration',
                  u'Decceleration', u'Decceleration', u'normal',
                  u'Decceleration', u'Decceleration', u'Decceleration',
                  u'Decceleration', u'Decceleration', u'Decceleration',
                  u'Decceleration', u'Decceleration', u'n

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 0, 3, 3, 3, 3, 3, 3, 3, 3, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [35]:
# Create a random forest classifier. By convention, clf means 'classifier'
clf = RandomForestClassifier(n_jobs=2)

# Train the classifier to take the training features and learn how they relate
# to the training y (the species)
clf.fit(train[features], y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=2, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [36]:
# Apply the classifier we trained to the test data (which, remember, it has never seen before)
test_data = clf.predict(test[features])
test_data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2,
       0, 0, 2, 2, 2, 2, 3, 0, 3, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0,
       2, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0,

In [37]:
# View the predicted probabilities of the first 10 observations
proba = clf.predict_proba(test[features])
print(proba)

[[ 1.   0.   0.   0.   0. ]
 [ 1.   0.   0.   0.   0. ]
 [ 1.   0.   0.   0.   0. ]
 ..., 
 [ 0.9  0.   0.   0.1  0. ]
 [ 0.6  0.   0.   0.   0.4]
 [ 0.2  0.   0.   0.1  0.7]]


In [38]:
#name = {'0':'normal','1':'Hard Acceleration','2':'normal','3':'Decceleration','4':'Right Turn','5':'Left Turn'}

preds = clf.predict(test[features])

In [39]:
#for x in np.nditer(preds):
      # print x

In [40]:
tb = pd.crosstab(test['marker'], test_data, rownames=['Actual Events'], colnames=['Predicted Events'])
import matplotlib.pyplot as plt
#tb.plot()
plt.show()
#tb.to_csv("cross_table.csv")
tb

Predicted Events    0  1   2   3  4
Actual Events                      
Decceleration      11  0  10  22  0
HardAcceleration   28  0  63  11  1
LeftTurn           10  0   0   0  3
RightTurn           6  3   0   0  0
normal            713  0   3   4  1

In [19]:
r = test['marker']
r.to_csv("test_original_with_index.csv")

In [220]:
list(zip(train[features], clf.feature_importances_))

[('Speed (Kmph)', 0.210351418542438),
 ('GyroScop_x', 0.035733114937772668),
 ('GyroScop_y', 0.040018141928882311),
 ('GyroScop_z', 0.05170210054622152),
 ('attitude_pitch', 0.088534539203622406),
 ('attitude_roll', 0.13178612355595079),
 ('attitude_yaw', 0.11263940650517971),
 ('acceleration_x', 0.072020177627249479),
 ('acceleration_y', 0.050513401382796717),
 ('acceleration_z', 0.079961254368350013),
 ('G_x_avg', 0.048620147840462126),
 ('G_y_avg', 0.078120173561074299)]

In [221]:
test.dtypes

Speed (Kmph)       float64
GyroScop_x         float64
GyroScop_y         float64
GyroScop_z         float64
attitude_pitch     float64
attitude_roll      float64
attitude_yaw       float64
acceleration_x     float64
acceleration_y     float64
acceleration_z     float64
G_x_avg            float64
G_y_avg            float64
marker            category
is_train              bool
dtype: object