In [118]:
import pandas
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
import time
import boto
from boto.s3.key import Key
import pandas as pd
from sqlalchemy import create_engine

In [119]:
filename_train = 'D:/Machine Learning/Bike sensor data/Test-Drive-Sasken/test-drive-ml-2_3_4.csv'
names_train = ['Speed (Kmph)','GyroScop_x','GyroScop_y','GyroScop_z','attitude_pitch','attitude_roll','attitude_yaw','acceleration_x','acceleration_y','acceleration_z','G_x_avg','G_y_avg','A_x_avg','A_y_avg','A_z_avg','marker']
data_train = pandas.read_csv(filename_train, names=names_train)

df_train = pd.DataFrame(data_train, columns=data_train.columns)
df_train = df_train.ix[1:]

df_train['is_train'] = np.random.uniform(0, 0, len(df_train)) <= .100
df_train.head()

Speed (Kmph)   GyroScop_x    GyroScop_y    GyroScop_z attitude_pitch  \
1         -3.6  0.561173856    0.04686249   0.092928469    0.554535052   
2         -3.6  0.283138305   0.014048797  -0.160364747    0.595711616   
3         -3.6   0.39914155  -0.143089995  -0.273033887    0.617707136   
4         -3.6  0.395565838  -0.022679988  -0.119658746     0.64502564   
5         -3.6  0.062787458   0.299148381  -0.059119448    0.660259827   

  attitude_roll  attitude_yaw acceleration_x acceleration_y acceleration_z  \
1  -0.009908888   0.003412455    -0.01252646   -0.353105843    0.313467264   
2  -0.009801454  -0.000722531   -0.100575335   -0.237562343    0.400585651   
3  -0.001267816  -0.033180496   -0.089344271    -0.23768124    0.295691907   
4   0.006303429  -0.057348863   -0.057160962   -0.234474435    0.416118652   
5    0.03877278  -0.031739561   -0.089133799   -0.264561832    0.242226958   

  G_x_avg G_y_avg A_x_avg A_y_avg A_z_avg  marker is_train  
1       0       0       0       0       0  normal     True  
2       0       0       0       0       0  normal     True  
3       0       0       0       0       0  normal     True  
4       0       0       0       0       0  normal     True  
5       0       0       0       0       0  normal     True

In [120]:
filename_test = 'D:/Machine Learning/Bike sensor data/Test-Drive-Sasken/test-drive-ml-5.csv'
names_test = ['Speed (Kmph)','GyroScop_x','GyroScop_y','GyroScop_z','attitude_pitch','attitude_roll','attitude_yaw','acceleration_x','acceleration_y','acceleration_z','G_x_avg','G_y_avg','A_x_avg','A_y_avg','A_z_avg','marker','trip_id','holizontalAccuracy','verticalAccuracy','altitude','longitude','latitude','timestamp']
data_test = pandas.read_csv(filename_test, names=names_test)

df_test = pd.DataFrame(data_test, columns=data_test.columns)
df_test = df_test.ix[1:]

df_test_copy = pd.DataFrame(data_test, columns=data_test.columns)
df_test_copy = df_test_copy.ix[1:]

del df_test['trip_id']
del df_test['holizontalAccuracy']
del df_test['verticalAccuracy']
del df_test['altitude']
del df_test['longitude']
del df_test['latitude']
del df_test['timestamp']

df_test['is_train'] = np.random.uniform(0, 0, len(df_test)) <= .100

df_test_copy[['Speed (Kmph)','GyroScop_x','GyroScop_y','GyroScop_z','attitude_pitch','attitude_roll','attitude_yaw','acceleration_x','acceleration_y','acceleration_z','G_x_avg','G_y_avg','A_x_avg','A_y_avg','A_z_avg','holizontalAccuracy','verticalAccuracy','altitude','longitude','latitude','timestamp']] = df_test_copy[['Speed (Kmph)','GyroScop_x','GyroScop_y','GyroScop_z','attitude_pitch','attitude_roll','attitude_yaw','acceleration_x','acceleration_y','acceleration_z','G_x_avg','G_y_avg','A_x_avg','A_y_avg','A_z_avg','holizontalAccuracy','verticalAccuracy','altitude','longitude','latitude','timestamp']].astype('object')
df_test_copy[['marker','trip_id']] = df_test_copy[['marker','trip_id']].astype('string')

In [121]:
d1_test = df_test[df_test['is_train']==True]
d1_train= df_train[df_train['is_train']==True]

d1_test[['Speed (Kmph)','GyroScop_x','GyroScop_y','GyroScop_z','attitude_pitch','attitude_roll','attitude_yaw','acceleration_x','acceleration_y','acceleration_z','G_x_avg','G_y_avg','A_x_avg','A_y_avg','A_z_avg']] = d1_test[['Speed (Kmph)','GyroScop_x','GyroScop_y','GyroScop_z','attitude_pitch','attitude_roll','attitude_yaw','acceleration_x','acceleration_y','acceleration_z','G_x_avg','G_y_avg','A_x_avg','A_y_avg','A_z_avg']].astype('float')
d1_train[['Speed (Kmph)','GyroScop_x','GyroScop_y','GyroScop_z','attitude_pitch','attitude_roll','attitude_yaw','acceleration_x','acceleration_y','acceleration_z','G_x_avg','G_y_avg','A_x_avg','A_y_avg','A_z_avg']] = d1_train[['Speed (Kmph)','GyroScop_x','GyroScop_y','GyroScop_z','attitude_pitch','attitude_roll','attitude_yaw','acceleration_x','acceleration_y','acceleration_z','G_x_avg','G_y_avg','A_x_avg','A_y_avg','A_z_avg']].astype('float')

d1_train['marker'] = d1_train['marker'].astype('category')
d1_test['marker'] = d1_test['marker'].astype('category')

In [122]:
print('Number of observations in the training data:', len(d1_train))
print('Number of observations in the test data:',len(d1_test))

('Number of observations in the training data:', 4512)
('Number of observations in the test data:', 1242)


In [123]:
features = df_train.columns[:15]
features

Index([u'Speed (Kmph)', u'GyroScop_x', u'GyroScop_y', u'GyroScop_z',
       u'attitude_pitch', u'attitude_roll', u'attitude_yaw', u'acceleration_x',
       u'acceleration_y', u'acceleration_z', u'G_x_avg', u'G_y_avg',
       u'A_x_avg', u'A_y_avg', u'A_z_avg'],
      dtype='object')

In [124]:
y = pd.factorize(d1_train['marker'])[0]
x = pd.CategoricalIndex(d1_train['marker'])

#x.append(y.tolist)
#print(x[2100:2157])
#y[2100:2157]

In [125]:
clf = RandomForestClassifier(n_jobs=3)

clf.fit(d1_train[features], y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=3, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [126]:
test_data = clf.predict(d1_test[features])
test_data

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [127]:
proba = clf.predict_proba(d1_test[features])
print(proba)

[[ 1.   0.   0.   0.   0. ]
 [ 1.   0.   0.   0.   0. ]
 [ 1.   0.   0.   0.   0. ]
 ..., 
 [ 0.9  0.   0.   0.   0.1]
 [ 0.8  0.   0.   0.   0.2]
 [ 0.9  0.   0.   0.   0.1]]


In [128]:
preds = clf.predict(d1_test[features])

In [129]:
sLength = len(df_test_copy['marker'])

#for x in np.nditer(preds):
df_test_copy['p_marker'] = pd.Series(preds , index=df_test_copy.index)

df_test_copy['p_marker'].replace(0, 'normal',inplace=True)
df_test_copy['p_marker'].replace(1, 'RightTurn',inplace=True)
df_test_copy['p_marker'].replace(2, 'HardAcceleration',inplace=True)
df_test_copy['p_marker'].replace(3, 'Decceleration',inplace=True)
df_test_copy['p_marker'].replace(4, 'LeftTurn',inplace=True)

In [130]:
#ts = int(time.time())
#data_file = df_test_copy.to_csv(str(ts)+".csv",index=False)

In [131]:
tb = pd.crosstab(d1_test['marker'], df_test_copy['p_marker'], rownames=['Actual Events'], colnames=['Predicted Events'])
#import matplotlib.pyplot as plt
#tb.plot()
#tb.to_csv(str(ts)+"_cross_table.csv")
#plt.show()
tb

Predicted Events  Decceleration  HardAcceleration  RightTurn  normal
Actual Events                                                       
Decceleration                51                27          0      31
HardAcceleration              9                87          0      95
LeftTurn                      0                 3          0      27
RightTurn                     0                 0          0       9
normal                       25                63          1     814

In [132]:
#keyId = "AKIAJM6HKMMJJO5MIK4Q"
#sKeyId= "j5RD68MBl5KYnKimWgrxxNSnvJzzazYFTMrGois+"
#fileName=str(ts)+".csv"
#bucketName="geo-code"
#files = open(str(ts)+".csv")
#conn = boto.connect_s3(keyId,sKeyId)
#bucket = conn.get_bucket(bucketName)
##Get the Key object of the bucket
#k = Key(bucket)
##Crete a new key with id as the name of the file
#k.key=fileName
##Upload the file
#result = k.set_contents_from_file(files)
##result contains the size of the file uploaded
#print('file uploaded successfully...')

In [133]:
df_test_copy['Line Group (Path ID)']= df_test_copy.index
df_test_copy['Order of Points']= df_test_copy.index

In [136]:
df_test_copy

Speed (Kmph)    GyroScop_x    GyroScop_y    GyroScop_z attitude_pitch  \
1     6.443999863   0.260009199   -0.57214129  -0.993046939    1.125423271   
2     6.443999863   0.201548591  -0.404839784  -0.596838415    1.132359494   
3     6.443999863   0.103397466  -0.381156564  -0.506013155    1.132720573   
4     6.443999863   0.146714509   -0.54722023  -0.412165105    1.139986431   
5     7.415999795   0.115684301  -0.506287754  -0.315160722     1.14566984   
6     7.415999795   0.298552513  -0.448548287  -0.191068336    1.157630879   
7     7.415999795   0.313219696  -0.750458002  -0.426279306    1.162502673   
8     7.415999795   0.319865644  -0.731475651   -0.35505569    1.167107137   
9     7.415999795   0.399995536  -0.647349894  -0.222454146     1.19115342   
10    7.415999795   0.396688849  -0.517618537  -0.215393737    1.222251913   
11    7.415999795   0.007638965  -0.534135222  -0.047110178    1.229440455   
12    7.415999795   -0.02045778  -0.719309449  -0.127815142    1.219758227   
13    7.415999795   0.474227697  -0.641242266  -0.363787949    1.239445459   
14    7.415999795   0.013997685  -1.334455967  -0.552875102    1.243348689   
15    7.415999795   -0.50394392  -1.173703074  -0.087574609    1.214769272   
16    7.487999726  -0.392004579   -0.88674283    0.41212818     1.19932977   
17    7.487999726   0.493955672  -0.061526578   0.007310397    1.223541979   
18    7.487999726    0.29711616   -0.55159384    0.02684122    1.268070362   
19    7.487999726   0.370203525  -0.604681671   0.024541765    1.312322046   
20    7.487999726   0.722775877  -0.051969513  -0.079898149    1.389940302   
21    7.487999726   0.777608871   0.271218061  -0.020416003     1.43146971   
22    7.487999726   0.367613465  -0.398083687   0.191229329    1.476141159   
23    7.487999726  -0.109560005  -0.594847262   0.193946049    1.503607216   
24    7.487999726    0.10109105  -0.038081951   0.056274001    1.508114039   
25    7.487999726  -0.523037493   0.092637323   0.356866062    1.480474405   
26    7.487999726  -0.263039827   0.687756062   0.393657237    1.431321738   
27    12.34800024  -0.144453645   0.680250406   0.221618399    1.396574255   
28    12.34800024  -0.214215547   0.590969205   0.280809432    1.385722771   
29    12.34800024  -0.414486498   0.577012241   0.511868596    1.351493871   
30    12.34800024  -0.080584981   0.471976995   0.104127407    1.314644968   
...           ...           ...           ...           ...            ...   
1213  40.82400054   -0.01966583   0.169036031   0.233264685    1.171852945   
1214  40.82400054   0.772565186    0.52315259  -0.112687267    1.169711601   
1215  33.48000069    0.00590889  -0.064356454   0.152521133    1.190593866   
1216  26.53199959  -0.064204045   0.064139865  -0.044516612    1.204486916   
1217  26.53199959   0.188563004   0.014023729  -0.167214453    1.221004979   
1218  26.53199959  -0.079476885  -0.066072688   0.134052619    1.208900143   
1219  26.53199959  -0.086921036  -0.257577837   0.022696991    1.242369051   
1220  26.53199959   0.037584547  -0.026763054  -0.189252838    1.249869973   
1221  26.53199959  -0.007638219  -0.020786753  -0.405654758    1.228937956   
1222  26.53199959  -0.764930248  -0.705980599  -0.317062497     1.19280747   
1223  24.08400021   0.082021981     -0.182255  -0.124874726    1.075368531   
1224  24.08400021   0.074623942  -0.010888781  -0.187980235    1.081021639   
1225  24.08400021    -0.0692489   -0.17882736   0.129532486     1.08448925   
1226  24.08400021  -0.027211521    0.02201114   0.308607578    1.083251454   
1227         23.4   0.005271534  -0.192847922   0.266101092    1.104951641   
1228         23.4   0.000443528   0.102212235  -0.125545636    1.093568499   
1229         23.4  -0.111920305   0.185396656  -0.017558377    1.096887576   
1230         23.4  -0.120114267   0.157085016   0.056264315    1.096430102   
1231         23.4  -0.074872918  -0.063746661   0.228883252    1.005688008   
1232         23.4  -0.15088

In [135]:
def f(row):
    if (row['marker'] == 'normal') & (row['p_marker'] == 'normal'):
        val = 'normal'
    elif row['marker'] == row['p_marker']:
        val = 'matched'
    else:
        val = 'not_matched'
    return val
        
df_test_copy['combined_marker'] = df_test_copy.apply(f, axis=1)
df_test_copy.to_csv("data.csv",index = False)

In [1]:
#import psycopg2, csv

#try:
 #   conn = psycopg2.connect("dbname='SensorFusionDatabase' user='sanni' host='sensorfusiondbinstance.cjz4wrixhzjb.us-west-2.rds.amazonaws.com' password='mysensorfusiondb'")
#   print("connected")
#except:
#    print ("I am unable to connect to the database")

#cur= conn.cursor()

#------------------------------------------------------------

#dataText = ','.join(cur.mogrify("(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)", tuple(row))for i, row in enumerate(reader))

#cur.execute('INSERT INTO "apple_sensor" VALUES ' + dataText)

#------------------------------------------------------------

#reader = csv.reader(open('data.csv', 'r'))

#for i, row in enumerate(reader):
    #print(i, row)
#    if i == 0: continue

#    cur.execute('''
#       INSERT INTO "apple_sensor" (
#            "Speed","GyroScop_x","GyroScop_y","GyroScop_z","attitude_pitch","attitude_roll","attitude_yaw","acceleration_x","acceleration_y","acceleration_z","G_x_avg","G_y_avg","A_x_avg","A_y_avg","A_z_avg","marker","trip_id","holizontalAccuracy","verticalAccuracy","altitude","longitude","latitude","timestamp","p_marker","Line_Group","Order_of_Points","combined_marker"
#        ) values %s''', [tuple(row)]
 #   )

#conn.commit()
#cur.close()
